name: Docker CI

on:
  push:
    branches: [main]
    paths:
      ["**/Dockerfile*", "docker-compose*.yml", ".github/workflows/docker.yml"]
  pull_request:
    branches: [main]
    paths:
      ["**/Dockerfile*", "docker-compose*.yml", ".github/workflows/docker.yml"]

jobs:
  docker:
    name: Docker Build Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build frontend Docker image
        run: |
          docker build -t solgogo-frontend:test ./frontend

      - name: Build backend Docker image
        run: |
          docker build -t solgogo-backend:test ./backend

      - name: Test Docker Compose configurations
        run: |
          docker compose config
          docker compose -f docker-compose.dev.yml config
